data/siteMetadata.json, layouts/ListLayout.js, layouts/PostLayout.js, package-lock.json, package.json, pages/index.js
remove tinytime library and use toLocaleDateString to add internationalization
=> Add support to Locale Date String

package-lock.json, package.json, postcss.config.js, tailwind.config.js
Nothing as exciting in tech as upgrading to a much better solution and then immediately having to reconfigure said solution in a different way for no particular reason, right @timlrx ? Haha
=> Upgrade Tailwind to 2.1.1 keeping jit (Just in Time) engine enabled per https://blog.tailwindcss.com/tailwindcss-2-1

.eslintrc.js
Add installed but missing eslint-plugin-react-hooks to .eslintrc plugins list.
=> add installed but missing eslint-plugin-react-hooks to .eslintrc

layouts/PostLayout.js
Closes #48 
Tested manually by deleting siteMetadata.twitter value
=> fix: make siteMetadata.twitter optional to fix TypeError

package-lock.json, package.json, tailwind.config.js
Modify jit configuration to have it working with fast refresh. Switch to using `cross-env` for better cross platform compatibility.
=> fix: jit config

lib/mdx.js, pages/blog/[...slug].js
=> fix: slug links for nested posts

scripts/generate-sitemap.js
=> Simplify string interpolation

lib/utils/files.js
=> chore: fix typo

lib/generate-rss.ts, lib/utils/files.ts, lib/utils/formatDate.ts, lib/utils/htmlEscaper.ts
Hello,
I did some change for the typescript implementation, on the `lib` folder.
The MR might need a squash and merge ?
Kind regards,
Gautier
=> Typescript

scripts/generate-sitemap.js
=> fix: restrict sitemap to mdx files in blog folder

package-lock.json, package.json
=> fix: code newlines

data/blog/introducing-tailwind-nextjs-starter-blog.mdx, data/blog/new-features-in-v1.mdx, lib/mdx.js
Fix issue in https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/151 and support both date type and date strings.
=> fix: support date type in blog frontmatter

components/SEO.js, pages/tags/[tag].js
Rss feed on tags were not working (it seems).
I created another component in SEO, the only difference being that they add a link to the rss tags.
=> feat: add topic rss feed to tag seo

package-lock.json, package.json
See related issue on rehype-prism-plus: https://github.com/timlrx/rehype-prism-plus/issues/9
=> fix: syntax highlighting for multiline code

components/comments/Giscus.js, components/comments/Utterances.js
=> feat: auto switch theme for giscus and utterances

css/tailwind.css
Clean fix for the spaces on the right side of the code block.
=> fix: code block space #209

package-lock.json, package.json
=> chore: upgrade to next 11.1.2

README.md
Thank you for such a cool template!
=> Add featured blog

css/prism.css, data/blog/new-features-in-v1.mdx, package-lock.json, package.json
Closes #223
E.g. the following code
```diff
- let foo = bar.baz([1, 2, 3]);
+ foo = foo + 1;
const foo = bar.baz([1, 2, 3]) + 1;
console.log(`foo: ${foo}`);
```
generates the following output
=> feat: upgrade rehype-prism-plus and add default diff css

package.json, pages/_app.js
=> fix: do not load socketio for next dev

.env.example, README.md, data/siteMetadata.js, pages/api/klaviyo.js
Hey :wave: !
Full disclosure, I work for Klaviyo! With that said, I am using this template for my own website and thought I would contribute to the repo if you don't mind!;
=> Add Klaviyo to Newsletter options.

data/siteMetadata.js, pages/_app.js
Hi,
Now you can choose the default theme in siteMetadata
#289
=> feat: customize default theme

data/siteMetadata.js, pages/_app.js
- Use 'system' as default theme
=> Allow default theme to be customized from config file

components/MobileNav.js
=> fix: add padding to align menu and theme button

data/blog/deriving-ols-estimator.mdx
=> docs: update post on escaping inline-math

README.md, data/blog/introducing-tailwind-nextjs-starter-blog.mdx, next.config.js
=> Add security headers - fixes #304

components/Card.js
=> fix: allow proj img to be optional

tailwind.config.js
=> fix: dark prose table header

README.md
my blog is now in the list 
I am using this template to make it
Thanks a lot for this template !!!
=> added my blog in the list :))

README.md
Also changed text to: "or with TypeScript" rather then "TS"
=> Remove script format from "or" text by removing indent

components/LayoutWrapper.js
aria-label will be picked from the site metadata instead of being a fixed value.
=> Accessibility Fix in LayoutWrapper

README.md
This add [astrosaurus.me](https://astrosaurus.me) to blog list.
=> add astrosaurus.me to blog list.

README.md
Add personal site and blog to README.md
=> add dhanrajsp.me to blog list

css/prism.css, lib/mdx.js, lib/remark-extract-frontmatter.js, package-lock.json, package.json
- Upgrade rehype-citation (breaking change, plugin now can automatically derive bib file from frontmatter)
- Upgrade tailwindcss (`prism.css` needs to change `border-opacity-0` to `border-transparent`)
- Upgrade nextjs
=> upgrade rehype-citation, nextjs, tailwindcss

components/Card.js, components/Footer.js, components/LayoutWrapper.js, components/MobileNav.js, components/NewsletterForm.js, components/Pagination.js, components/Pre.js, components/ScrollTopAndComment.js, components/SectionContainer.js, components/TOCInline.js, components/ThemeSwitch.js, components/comments/Utterances.js, components/social-icons/index.js, css/prism.css, layouts/AuthorLayout.js, layouts/ListLayout.js, layouts/PostLayout.js, layouts/PostSimple.js, lib/utils/files.js, package-lock.json, package.json, pages/404.js, pages/_document.js, pages/index.js, pages/projects.js, pages/tags.js
lint all files through the new [tailwind prettier plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) - `prettier --write "**/*.js"`
=> prettier tailwind

README.md
=> Add alfoncode.com website

css/prism.css, data/blog/new-features-in-v1.mdx, tailwind.config.js
- fix: override table styling for prism token (https://github.com/timlrx/rehype-prism-plus/issues/31)
- use optimizeUniversalDefaults for tailwind config (https://github.com/tailwindlabs/tailwindcss/discussions/7317)
- docs: add lang for code block examples
=> tailwind prism css changes

lib/mdx.js
=> remove redundant frontmatter parsing

pages/api/klaviyo.js
=> fix: eslint warning

README.md, data/blog/introducing-tailwind-nextjs-starter-blog.mdx, data/siteMetadata.js
I should have added this in the original CSP pull request already.
=> Add setup info regarding the CSP

README.md
Thanks for making this great template!
=> chore: add personal website to examples

tailwind.config.js
https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/404
=> fix: include tailwind style in mdx files

README.md
A blog of a Chinese front-end developer 狂奔小马的博客
=> Add my blog to examples

README.md
added my personal blog to sites list
=> Add a new example website to README.md

pages/404.js
=> feat: add title when page not found

README.md
Add my blogs https://0xchai.io and https://devahoy.com to the example list.
=> Add my websites to example list

README.md
We're using your template this v0 and are loving the v1 also! Thanks
=> add our example in the readme

README.md
=> add dalelarroder.com's source code

README.md
Hi there, 
Thank you for the amazing template. As someone who recently took up coding (8 months ago) this was a great learning tool.  I created a website for a friend using your template and was hoping you could add it to the other examples in the readme. 
I've included the link to the website and public repo.
cheers
=> add Cwarcup's podcast website to readme example

components/analytics/Posthog.js, components/analytics/index.js, data/siteMetadata.js
PostHog is the open source platform for your product data, complete with event pipelines, a data warehouse, and an API. 
PostHog analytic include free tier up to 1 million events or use self-hosting.  learn more https://posthog.com
=> add PostHog analytics - The product analytics suite you can host yourself

README.md
I've added my personal blog that has been created using this template to the README.
=> Add jmalvarez.dev to README

README.md
Hello,
Thanks for this template!
I propose to update the Lighthouse report's test result.
Thanks :)
=> docs: update Lighthouse report's link

README.md
Just a minor update on `README.md` for my blog's description. I hope this pr will get merged 🙏.
Thank you for your good work and have an excellent day 🎉
=> Update Leo's blog description on README.md

app/blog/[...slug]/page.tsx
Fix: #676 
Thanks, @MrRhodes for the fix. Did not realize there was a difference, but apparent there is!
=> fix: ld json serialization

README.md
=> update readme on static build

README.md
Adding my personal blog to the list of examples. I love it so much I kept the link to the template in the footer. It's pretty barebone for now but thanks to you I can spend more time writing articles instead of coding my blog :D. Not sure how it will evolve over time.
=> Add ben.codes in V2 examples

components/ThemeSwitch.tsx
=> fix: revert to use resolvedTheme

README.md
Thanks @wanoo21 for the contribution! 🎉
=> Add link to astro template

.github/ISSUE_TEMPLATE/bug_report.md, app/tag-data.json, package.json, yarn.lock
=> upgrade to next 13.5.6

README.md
Add a mention to Remix-run alternative per conversation https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/710#discussioncomment-7321796
=> chore: update readme to mention remix-run alternative

README.md
I have been using the v1 blog for more than 6 months and recently switched to V2. Really love the simplicity and structure of the overall code @timlrx . Great job maintaining it!
=> Add thetalhatahir.com

README.md
@timlrx My blog is using version 2 of your template. So i moved it to the correct location in readme.md file
Please approve! 
Many thanks!
=> Move blog to v2 in readme.md

README.md
Add my personal website to example v2
=> Add contrails.space to README.md

css/tailwind.css
=> fix katex overflow

app/sitemap.ts
I am creating this PR because I think posts that are in draft status should not be added to the sitemap.
I would appreciate your feedback. 🙏
=> draft posts are not included in the sitemap

README.md
Thank you so much for making this, and was really cool to see you also went to UBC!
=> Adding example of site using v2 of template to README

README.md
Thanks for creating this repository !
=> Update README.md about V2 example

README.md
I added the link to my own personal blog site.
=> docs(readme): Add another blog V2 example 

README.md
thank you for creating and sharing this project!
=> Add an example of template in use to README.md

README.md
Created my blog using tailwind-nextjs-starter-blog, thank you!
I added my page to the Examples V2
=> docs: Added Zsebinformatikus to Examples V2

contentlayer.config.ts, package.json, scripts/rss.mjs, yarn.lock
Upgrade next 14.1, tailwind 3.4 and pliny 0.1.7. Also upgraded to github-slugger 2.0.0
Fix https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/833
Fix https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/817
=> feat: upgrade next 14.1, tailwind 3.4 and pliny 0.1.7

README.md
=> chore: modified the domain

README.md
=> feat: Add Trillum's blog to examples

components/ThemeSwitch.tsx
Hi! Here's the PR for the smal bug with the post-banner layout!
=> Fix z-index in ThemeSwitch.tsx

README.md
Loved the theme but I have now switched to a different framework and thus no longer fair to claim space here!
Thanks for all your hard work!
=> remove markpitblado.me from README v2

README.md
Hi there! Just adding [ my project link ](https://www.meamenu.com/) to the list of v2 sites. I really loved the work put on this template, i did some PR requests across the other projects that helped me to create mine. 
I used cool dependencies such as framer-motion for custom animations, waline for blog comments (it allows to create comments as admin and doesn't require visitor email to comment) and primereact for upload form. This is the only blog of the list in italian.
=> add meamenu.com to project examples V2

app/seo.tsx
Fix https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/911
=> standardize description and og:description

components/social-icons/index.tsx
=> Fix email domain validation

README.md
more doc on how to print a url taking BASE_PATH into account
=> `process.env.BASE_PATH` doc

app/tags/[tag]/page.tsx
Fix Invalid Tag Page Returns Status 200 Instead of 404 #988
=> Fix issue #988

components/ThemeSwitch.tsx
Resolve Add Accessible Name to Theme Switcher Button #990
=> Resolve Issue #990

README.md
Update README.md to add website bmacharia.com
=> Update README.md to add website bmacharia.com

README.md
Provide source link for Trillium blog
=> chore: Provide blog source for Trillium blog

data/blog/release-of-tailwind-nextjs-starter-blog-v2.0.mdx
=> chore: update release-of-tailwind-nextjs-starter-blog-v2.0.mdx

data/projectsData.ts
Great template! thanks for creating this!
Commas are not needed here.
Prettier also corrected it for me when I simply save the file in VScode.
=> Fix: syntax error

components/Footer.tsx, components/social-icons/icons.tsx, components/social-icons/index.tsx, data/siteMetadata.js
=> Add the Medium to Footer

README.md
Just upgraded my blog to v2, so I'm removing it from **Examples V1** list to add to **Examples V2** list.
Thank you for your awesome work!
=> Add my blog to Examples V2

scripts/rss.mjs
=> fix: static build should write to out folder

README.md, faq/deploy-with-docker.md
=> Add faq to deploy with docker

README.md
Adding another example (my first) of using this boilerplate to the list.  Thanks for all your effort building this Tim!
=> Add blog to list of examples

README.md
Hi Tim, i am excited to sharing my blog and join your list v2. Thanks for your great works.
=> add my blog

README.md
This PR adds my blog, [Wahyu Ikbal Personal Website](https://www.wahyuikbal.web.id), to the list of projects using this template.
Let me know if there’s anything else I should adjust.
=> Added my Website blog to README 

README.md
Since i use the template i would love to showcase the blog here as well. 
Thanks :)
=> Add MichaelScheiwiller to examples v2

README.md
added htpts://www.farhad.my to v2 section of readme
=> Add new website showcase

README.md
Add a blog illustrating the use of the tailwind-nextjs-starter-blog with Next.js v15 and app router directory structure.
=> Update README.md to add utanzu.com blog
