timlrx/tailwind-nextjs-starter-blog

- package.json
Adding "env" before setting environmental variables makes it cross-platform (i.e. work on Windows in addition to Unix / Mac).
Tested Windows 10 x64
"@infinity @jamie-penney env NODE_ENV=test mocha --reporter spec will use the declared environment variable in a natively cross platform fashion, but the key is it is used by npm in an ad hoc and one-time fashion, just for the npm script execution. (It's not set or exported for future reference.) As long as you're running your command from the npm script, there's no issue. Also, the "&&" must be removed when doing it this way. – estaples Apr 5 '18 at 16:10 " Source: https://stackoverflow.com/a/27090755
> Improve Windows compatibility for npm run analyze

- components/ThemeSwitch.js
- components/social-icons/index.js
feature:
If there's no social link in siteMetadata.json, it can hide icons automatically.
bug:
useTheme is not working in the first render.
> Add feature and fix a bug

- next.config.js
Closes #20 
No visible changes as far as I can tell 😀
```
StrictMode is a tool for highlighting potential problems in an application. Like Fragment, StrictMode does not render any visible UI. It activates additional checks and warnings for its descendants.
Note:
Strict mode checks are run in development mode only; they do not impact the production build.
[...]
When strict mode is enabled, React compiles a list of all class components using the unsafe lifecycles, and logs a warning message with information about these components, like so:
strict mode unsafe lifecycles warning
Addressing the issues identified by strict mode now will make it easier for you to take advantage of concurrent rendering in future releases of React.
```
Source: https://reactjs.org/docs/strict-mode.html
Team Hooks …
> Enable React Strict Mode in next.config.js

- package-lock.json
- package.json
This would close #11 for Windows developers using GitHub Desktop.
(In other words, I can commit normally & the husky hooks will run -- which wasn't true with ^4.3.7 even after npm install.)
> Update husky (^4.3.7) to latest (^6.0.0)

- layouts/ListLayout.js
- layouts/PostLayout.js
This pull request fix a typo in ListLayout and PostLayout: `siteMetdata` -> `siteMetadata`
> Fix a typo in ListLayout and PostLayout

- components/ThemeSwitch.js
Bug: Incorrect theme toggle button on first load.
Fix: Added `resolvedTheme` to the conditionals.
On the very first load, the value of `theme` in `ThemeSwitch.js` will be `'system'`. So, the condition `theme === 'dark'` will always be `false` and the site will display the moon button even though it's already in dark mode. In other words, the theme toggle button have to be clicked twice to get to light mode.
You can reproduce the bug by opening the site in incognito.
> fix: correct invalid theme toggle on first load

- lib/generate-rss.js
When parsing descriptions and titles with characters like '&', '<', etc. feed was broken. This regex swaps these characters with their HTML entity equivalent.
> Add convertStringToHTML function to prevent RSS encoding issues

- lib/mdx.js
If there is an unexpected file error, eg `.DS_Store` common in macOS
I'm a beginner, but this works 😊
```
TypeError: Cannot read property 'join' of undefined
at eval (webpack-internal:///./layouts/ListLayout.js:37:86)
at Array.filter (<anonymous>)
at ListLayout (webpack-internal:///./layouts/ListLayout.js:36:35)
```
```
TypeError: Cannot read property 'map' of undefined
at eval (webpack-internal:///./pages/index.js:134:40)
at Array.map (<anonymous>)
at Home (webpack-internal:///./pages/index.js:72:84)
```
> Remove Unexpected File

- lib/generate-rss.js
- lib/utils/htmlEscaper.js
- package-lock.json
- package.json
I replaced the new `convertStringToHTML` function with the [html-escaper](https://www.npmjs.com/package/html-escaper) module [(GitHub repo)](https://github.com/WebReflection/html-escaper).
According to the developer of this module:
> do not ever replace one char after another if you are transforming a string into another
Because it might produce unexpected/unwanted results [like this](https://github.com/WebReflection/html-escaper#why).
> Swap convertStringToHTML with html-escaper module

- components/comments/Giscus.js
Fix #154.
The error:
It is caused by a recent update in giscus: https://github.com/laymonage/giscus/commit/ae401f85cea100381554f7a739cb7fe7a415f2b4
The update was done to prevent `iFrameResizer` from interfering with other `<iframe>` elements on the page. (I think by default it applies to all `<iframes>` that exist on the page.)
However, the error exists because you use the `giscus-frame` class for the div. The `giscus-frame` is meant to be used by giscus' `<iframe>` tag only, and it's managed by the client script. You should use the `giscus` class instead to tell giscus where to put the `<iframe>`.
From the docs:
> fix: rename `giscus-frame` class to `giscus`

- pages/blog/[...slug].js
Hello,
I found a little something on you pr for the translation demo. 
The `locale` should be outside  `params` scope, Next js documentation is very unclear on that point. That's why you had to enable the Fallback.
(Thank you a lot for the demo ! It's going to be very useful for my own blog !)
> chore(slug): added ssr for other locales

- components/Pre.js
Fix #168.
The `textContent` property doesn't preserve line breaks. As a result, copying code using the button in the `<Pre>` component, e.g.
```js
theme: {
colors: {
primary: colors.teal,
gray: colors.trueGray,
...
}
...
}
```
results in the following when pasted:
```js
theme: {    colors: {      primary: colors.teal,      gray: colors.trueGray,      ...    }  ...}
```
By replacing `textContent` with `innerText`, line breaks are preserved.
> Use `innerText` to copy code content

- package-lock.json
- package.json
Fix #173 
Updated rehype-prism-plus package to use `refractor/lib/all.js` instead of the default export `refractor/lib/common.js`. We should be able to parse all 258 languages!
> fix: support all prism and refractor lang

- lib/remark-toc-headings.js
TOC won't work if `remark-autolink-headings` option `behavior` is set to `append`
> fix: toc issue with remark-autolink-headings

- lib/utils/kebabCase.js
- package-lock.json
- package.json
This MR force to use `github-slugger` for tags. This allows non-latin tags to work properly.
Closes #197
> fix: non-latin tags don't cause error

- css/prism.css
When enabling line numbers using `showLineNumbers` in a MD code block, the line numbers were left aligned causing the code from Line 1-9 to be slightly on the left than for code from L10 onwards. 
This PR fixes the above bug and right aligns the line numbers (following IDE conventions), and if merged code blocks will look like 
--- 
This also follows the same way IDEs represent line numbers,
- VSCode:
- WebStorm:
> fix: make line numbers in code block right aligned for a consistent UI

- lib/remark-toc-headings.js
The `toString` function in `hast-util-to-string` only works on text nodes but not inlineCode. `mdast-util-to-string` is more general and extracts the value of all nodes. Fix #278
> fix: parse inline code headings to string

- README.md
Hi,
I've updated the `npx degit` and `npm start` code blocks to have separate lines.
With that, starters can copy a command without manually highlighting it with their mouse.
I hope it makes sense.
> Improve starter experience

- package-lock.json
- package.json
This would bump nth-check to 2.0.1 and remove the dependabot warning
> chore: upgrade svgr

- css/tailwind.css
- tailwind.config.js
This pull request encompasses three closely related changes.
See the changes live here https://tailwind-nextjs-starter-blog-alexanderzeilmann.vercel.app/blog/github-markdown-guide
In CSS both `::before` and `:before` work, but `::before` is preferred.
Tailwind, however, accepts only the double-colon syntax, i.e. `'code:before': {content: 'none', }`
has no effect at all in `tailwind.config.js`, but `'code::before': {content: 'none', }` does.
**Changes: Replace `:before` and `:after` by `::before` and `::after`**
Rendering before the change:
Rendering after the change:
Using the `before`-pseudo element to style the list-items seems to be not working in current browsers.
The new way is using the `::marker` pseudo element.
**Changes: Add the following in `tailwind.css`**
```css …
```
> Use '::' for pseudo-classes & ::marker

- components/comments/Disqus.js
- next.config.js
1. Fix unable to load external js (Google Analytics and comment function), because Content Security Policy did not add the above to the whitelist #307 
Reproduce: https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1
2. Fix unable to get disqus config of shorname
> fix: can not load external script & Unable to get disqus config of shorname

- css/tailwind.css
- package-lock.json
- package.json
- pages/_document.js
- Fix some style changes that were reverted when upgrading from tailwind 2.0 to 3.0, namely on the footnotes and citation spacing.
- Move smooth-scroll to HTML body as it is it is now supported in tailwind 3.0
> Fix citation styles

- components/analytics/Umami.js
- components/analytics/index.js
- data/siteMetadata.js
I added support for [umami](https://umami.is) to [my blog](https://github.com/alaq/adrien.sh).
Umami is a self hosted analytics solution. I chose it because for some reason even Plausible self hosted was blocked by uBlock Origin. I figured I would offer to have the changes upstream as well.
Feel free to close this if it is not wanted.
> feat: add support for umami analytics

- components/ScrollTopAndComment.js
The current version use "opacity" to control the display state of the button, but when it is hidden, the mouse can still click on the button in the lower right corner
> fix: should use visibility to control display state of scroll top button

- lib/utils/kebabCase.js
In this variant (from the master branch), we can use the Cyrillic alphabet for the tag's name.
> chore: ability to use the 'cyrillic' alphabet

- tailwind.config.js
Added `!important` to a tag hover state for tailwind prose plugin to fix #342.
Alternatively, tailwind 3.0 supports [element modifiers](https://tailwindcss.com/docs/typography-plugin#element-modifiers) directly on prose component, but this would require refactoring the styles to the respective prose sections.
> fix: hover state for a tag in prose

- scripts/compose.js
If for any reason the `data/blog` directory is not present, the script fails. This change creates the `data/blog` directory if it doesn't yet exist to prevent error.
> Create `data/blog` directory if missing

- README.md
This adds [Slightly Sharpe](https://slightlysharpe.com) and the [b00st blog](https://blog.b00st.com) to the readme list.
> :notebook: add Tincre downstream blog properties

- components/comments/index.tsx
This is a small change in the `typescript` branch that fixes #357
> Adding `div id="comment"` to fix #357

- lib/remark-code-title.js
Fix https://github.com/timlrx/rehype-prism-plus/issues/29
Code title should be inserted relative to the parent, not the root component as it may be a child itself e.g.
````
<div style={{height: '300px', overflow: 'scroll'}}>
```json:fileName.json
A very long code snippet
```
</div>
````
> fix: insert code title relative to parent

- scripts/generate-sitemap.js
This PR...
1. Excludes drafts from the sitemap
2. Includes typescript pages
thus, resolving bug https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/366
> Exclude drafts from the sitemap, added typescript file to glob

- next.config.js
- package-lock.json
- package.json
- pages/_app.js
- pages/_document.js
- tailwind.config.js
As discussed in https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/370 this PR replaces Google Fonts with Fontsource.
See it live [here](https://tailwind-nextjs-starter-blog-drqw3td3d-alexanderzeilmann.vercel.app/).
> Replace Google Fonts with Fontsource

- next.config.js
Fix https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/304#issuecomment-1036579448
I think the best way to do it would be to keep the `max-age` and `includeSubDomains` but exclude `preload` by default.
To quote [HSTS preload org](https://hstspreload.org/):
> If you maintain a project that provides HTTPS configuration advice or provides an option to enable HSTS, do not include the preload directive by default. We get regular emails from site operators who tried out HSTS this way, only to find themselves on the preload list by the time they find they need to remove HSTS to access certain subdomains. [Removal](https://hstspreload.org/#removal) tends to be slow and painful for those sites.
Without the preload option ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/St …
> exclude preload from hsts header

- components/comments/Giscus.js
- data/siteMetadata.js
I added some properties for giscus app.
I hope I can be of some help to you. : )
> feat: add giscus config properties

- next.config.js
The existing unused loader config interferes with importing images locally with `next/image`
> fix: remove unused loader config

- README.md
Recently, I started working on a hobby project of mine whose purpose is to help & support upcoming artists and I decided to use the Tailwind Nextjs Starter Blog, which was the perfect fit for my case: finding something that is easy to modify, use and deploy. 
As it seems like on the site, I modified a lot on the "core" of Tailwind Nextjs Starter Blog and I also separated two blog parts: the actual blogging feature for my site and the lyrics part: they also generate their own sitemap, tags and RSS files, and the greatest part of it that it was really easy to add, because nowadays, sadly, I don't really have the time to work on a personal project. This is why I'd like to recommend Tailwind Nextjs Starter Blog to everyone. 👍
> Add a new example website to README.md

- components/ScrollTopAndComment.js
This pull request updates the `ScrollTopAndComment.js` component to only render the comment button in cases where a comment provider is specified at `siteMetadata.comment.provider`.
Granted, the theme default is to specify a provider, but, in cases where that provider is cleared and set to an empty string, the comment button still renders but directs users to a commenting implementation that isn't rendered.
> Render floating comment button only if a provider is specified

- README.md
zsh will throw an error for unquoted #
```zsh
(base) (⎈ |minikube:default) % degit https://github.com/timlrx/tailwind-nextjs-starter-blog#contentlayer
zsh: no matches found: https://github.com/timlrx/tailwind-nextjs-starter-blog#contentlayer 
```
Wrapping the git urls in ' ' fixes it, and it still works fine in bash
> Fix Quick Start install examples for zsh by adding single quotes

- components/ScrollTopAndComment.js
- package-lock.json
- package.json
Fix #436 
We are already using the `smooth-scroll` class from tailwind and can remove the polyfill.
> fix: remove smoothscroll-polyfill

- components/comments/Giscus.js
- components/comments/Utterances.js
- components/comments/index.js
Mapping is automatically picked up by giscus and utterances. No need to parse it on our end. Fix #437
> fix: mapping property in comments

- components/MobileNav.js
when we scroll the  page and try to open sidebar, their is some gap between the navbar and top of the sidebar which can spoil user experience.
i converted sidebar to fullscreen and added close sidebar button inside itself.
> fixed glitch in mobile navbar

- layouts/AuthorLayout.js
- layouts/ListLayout.js
Adds missing classes to address visual inconsistency between these elements on a few pages in dark mode.
> Fixes inconsistency in styles for divider on author and list layouts in dark mode

- components/SEO.js
- layouts/PostLayout.js
BlogSEO images were hardcoded to be locally sourced only. This change performs a simple check (i.e., `http` present in URI).
> frontmatter images can now be external

- README.md
The website https://the-all-javascript-blog.vercel.app does not exist anymore and I've removed it from the README.
> Remove broken website link from README

- README.md
Netlify does support next/images and other new features of next.js now
> Update Readme for Netlify's updated Next.js runtime

- README.md
- package.json
The deployment to GCP uses the `gcloud app deploy` script which compiles the `next.config.js` at runtime, however the  `@next/bundle-analyzer` is a `devDependency` so the deployment stage will fail.
Added instructions for deploying to GCP (Google App Engine) to `README.md`
> Modify configuration for GCP deployment

- app/blog/[...slug]/page.tsx
- app/layout.tsx
- contentlayer.config.ts
- layouts/PostLayout.tsx
- package.json
1.  chore: layouts/PostLayout.tsx use main branch for editUrl
also I sugguest this repo change from `master` to `main` branch
2. fix: import missing katex css
no katex css causing my exists formula display wrong
4. chore: tags can be empty, set default value to avoid compilation failure
my blog was migrated from other SSG to this one. and not all posts have the `tags` frontmatter.
5. fix: fix compile error for non-latin slug blog posts (I do not have this issue when I was using the very early v2 version before this pr https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/658 )
6. enable ignoreMissing option for rehypePrismPlus
before pr #658 , this was enabled and it works fine for my migrated blog.
7. fix(build): add mising `@types/mdx` required by "import type { MDXComponents } …
> v2 misc changes

- scripts/compose.js
Posts and summaries can often have punctuation that breaks markdown parsing without wrapping them in quotes
> Add quotes to title and summary

- package.json
Add new `app` directory of next.js 13 for lint. Keeping `pages` for now as they can coexist as people upgrade
> Add missing directory to lint command

- app/tags/[tag]/page.tsx
when tag is not English, the Tag&Blog tab can not match the right blogs, and the title of web site display not correct
> fix non-english tags filter failed, display error

- app/tags/[tag]/page.tsx
`allCoreContent` checks for the draft state based on NODE_ENV which is the correct behavior. This check is redundant and is causing the tags page to skip drafts in development.
> fix: hardcoded check for draft in development

- contentlayer.config.ts
I missed these changes in #700 
This PR will make sure that `tag-data.json` includes drafts in development.
Verified locally
> fix: include drafts in tag data during development

- app/tags/[tag]/page.tsx
In the `/tags/<tag>` page, the posts were not sorted, so I added a `sortPosts` function call
> fix: sort posts in tags page

- contentlayer.config.ts
Fix for the missing image in the JSON/LD structured data.
After fix:
> bugfix: Fix for missing image in ld+json blob

- README.md
Hey! Just adding my blog to the examples list. Much love for this starter template—I've been developing on the V1 template for about 9 months now, and the recent V2 release was what really motivated me to finish up and get everything done and dusted. Thank you so much for maintaining/developing such a cornerstone to the webdev/Next.js/blogging community!
> Add enscribe.dev to V2 examples

- scripts/rss.mjs
as generateRSS get last build date from first post, so we need to use sorted posts, otherwise the `lastBuildDate` value is wrong
> fix: use sort posts for rss, fix lastBuildDate

- components/Header.tsx
- components/MobileNav.tsx
- components/SearchButton.tsx
- components/ThemeSwitch.tsx
- layouts/ListLayoutWithTags.tsx
- layouts/PostBanner.tsx
- prettier.config.js
When formatting with prettier the tailwind HTML classes do not reorder automatically following the [recommended class order](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted) from [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#installation) even though this plugin is part of the dependencies of this project
The plugin was not added to the prettier config
I added the plugin in the config (first commit)
ran prettier on the components directory (second commit)
> fix prettier-plugin-tailwindcss not being used

- app/Main.tsx
Currently when performing a [Lighthouse](https://developer.chrome.com/docs/lighthouse/overview/) analysis of the [demo deployment](https://tailwind-nextjs-starter-blog.vercel.app/) of this template, the accessibility (a11y) score is 92 for both mobile and desktop with the following warnings:
* Background and foreground colors do not have a sufficient contrast ratio.
* Elements with visible text labels do not have matching accessible names.
Having the `aria-label` in the "Read More" link element of the post list item more closely match the tag's text ("Read more") increases the accessibility score to 96 for both mobile and desktop.
The color contrast warning can be fixed with different primary/secondary colors in the Tailwind configuration, but I think changing that should be up to @timlrx …
> Accessibility improvement: match aria-label to tag text for "read more" links

- app/tags/[tag]/page.tsx
For chinese tag name in devlopment mode will get error below:
_Error: Page "/tags/[tag]/page" is missing param "/tags/%E6%97%A5%E8%AE%B0" in "generateStaticParams()", which is required with "output: export" config._
Should be fixed with encodeURI method.
> feat: support chinese tag name

- README.md
- data/blog/introducing-tailwind-nextjs-starter-blog.mdx
Noticed some parts of the readme an demo blog posts still ref .js files that have been renamed to .ts
> Updated file names to use .ts rather than .js

- data/projectsData.ts
Without this, I get a build failure due to the TS checker.
> Add type to `projectsData.ts`

- data/siteMetadata.js
Choosing to store Umami tracking data in the US (instead of the EU, which may have been the historic default) actually requires loading a different script and setting a different CSP header (since the data instead goes to `us.umami.is` instead of `analytics.umami.is`).
I wasn't able to tell this without a little poking around and pestering folks on Discord / reading of https://github.com/timlrx/pliny to realize there was an option to do so.
Discord thread: https://discord.com/channels/951898446804172840/1195052582645801010/1195055451285504040
I'm happy to tweak the language or make other updates, but this at least would give someone a thread to pull on. I spent a fair amount of time trying to figure out what could be going wrong since Umami handles the (misdirected) tracking requests fine …
> docs: add example of src overwriting for US umami.is tracking

- .env.example
Just a minor update to the .env.example file to point the user to where the API Key and List ID are.  Not that it was difficult to find, but I figured I'd make it even quicker.
> Add quick links where to find EmailOctopus API key and List ID

- app/layout.tsx
There is an issue with layout shifting when clicking the navbar as shown in the image below. 
I resolved it by adding padding-left to the body tag.
> fix: layout shifting issue with navbar caused by scroll bar

- components/ThemeSwitch.tsx
While the `ThemeSwitch` mounts there's a potential for the buttons to be shifted to the left if it loads in slowly.
Moving the conditional rendering inside the `<svg/>` keeps the spacing open for the button to load in properly.
> feat: Move conditional rendering inside svg to prevent layout shift

- components/Comments.tsx
Incase if someone does not have any commenting platform enabled, the code will still show the Load Comments button.
This PR fixes it and only shows the Load Comments button if a commenting platform is provided.
> fix: update comments component incase of no provider

- data/blog/guide-to-using-images-in-nextjs.mdx
`data/img/ocean.jpg` appears to be unused throughout the project. All references are currently  `/static/images/ocean.jpg`.
> chore: fix typo (wrong path)

- components/ThemeSwitch.tsx
- package.json
- yarn.lock
The current implementation doesn't allow changing back to system once you changed the theme once since it's stored in localstorage by `next-themes`. This PR adds a `RadioGroup` to choose from all three states similar to https://tailwindcss.com/.
For an example of how this looks like in action see https://pavel.pink/ / https://github.com/pavelzw/blog
https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/29506042/28d51147-b678-49bd-93df-8d29779f1b0a
> Add system to ThemeSwitch

- README.md
Fix yarn workaround for Windows.
```powershell
npx degit 'timlrx/tailwind-nextjs-starter-blog'
yarn
➤ YN0000: ┌ Resolution step
...
➤ YN0000: └ Completed in 16s 814ms
yarn dev
Unbound variable "PWD"
set PWD="$(pwd)"
yarn dev        
Unbound variable "PWD"
$env:PWD = $(Get-Location).Path
yarn dev
▲ Next.js 14.2.3
- Local:        http://localhost:3000
✓ Starting...
Warning: Contentlayer might not work as expected on Windows
✓ Ready in 3.5s
Contentlayer config change detected. Updating type definitions and data...
successCallback C:/Users/borex/code/test/.contentlayer
(node:796) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node …
```
> Fix yarn workaround for Windows

- README.md
Hi there!  Just adding my personal website link to the list of v2 sites.  Love the template and really appreciate all your hard work.
Related to #849, I have this working using `remark-github-blockquote-alert`.  I appreciate getting this added in officially though.  GitHub's alerts are great.  You can see an example [here](https://www.joshhaines.com/blog/book-shelf/xlr8) of my implementation.
> add JoshHaines.com blog reference for v2

- README.md
- app/layout.tsx
- contentlayer.config.ts
- data/blog/introducing-tailwind-nextjs-starter-blog.mdx
- package.json
- yarn.lock
Added supported for https://github.com/jaywcjlove/remark-github-blockquote-alert, as suggested by @jdhaines.
Modified the original release blog post with a notice to prevent confusion - fix #924 
> [!CAUTION]
> This is the README of version 1 of the template. It is kept for historical reasons, but is no longer supported. It also serves as a nice example of [Github Alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts). For the actual documentation, please refer to the [Github repository](https://github.com/timlrx/tailwind-nextjs-starter-blog).
> Add Github alerts feature

- components/Header.tsx
- components/MobileNav.tsx
- components/SearchButton.tsx
- components/ThemeSwitch.tsx
Added hover highlight color classes to Header links/SVGS, ThemeSwitch menu
Changes in this PR:
- Hold off render of theme svg until mounted
- Added `<Blank />` svg as placeholder until mounted 
- Navigation links hover in `tailwind` primary color
- ThemeSwitch menu item hover with `{ active }`
- Use same  highlighting as the current `<SearchButton />`
> Add highlighting to Nav links, ThemeSwitch dropdown

- components/MobileNav.tsx
Current mobile drawer doesn't take advantage of accessibility offered by `headlessui`
Used [`headlessui/Dialog`](https://headlessui.com/v1/react/dialog) as an example to refactor the `MobileNav` drawer
- Move close button to bottom of drawer HTML so it is not auto selected when entering `MobileNav`
- Kept current `MobileNav` styling
- Changed to `Dialog` as base component
- Allows for tab press to stay within `Dialog`
- Allows for esc press to close `Dialog`
<details>
<summary>Before Changes</summary>
</details>
<details>
<summary>After Changes</summary>
</details>
> Refactor MobileNav to use headlessui

- components/ThemeSwitch.tsx
This PR fixes the alignment issue of the button within the ThemeSwitch component. The button was not properly centered within its container, causing it to appear misaligned in the navigation bar. This fix ensures that the button is vertically centered.
- Applied `flex` layout and alignment classes to the div containing `Menu.Button` in `ThemeSwitch.tsx`.
> Fix button alignment in ThemeSwitch component

- components/Link.tsx
[My blog's article](https://umihi.co/blog/20221226-login-aws-console-by-cli-credentials) has URL references at the end, and it create extra right margin on entire mobile layout. I confirmed that adding `className="break-words"` on `<a>` tags fixed that.
| **Before** | **After** |
| ------------- | ------------- |
| ![スクリーンショット 2024-07-07 11 32 36](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/39179585/93358cc1-c3c0-496a-8baa-2307fe4a2966) | ![スクリーンショット 2024-07-07 11 32 31](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/39179585/a6398536-a626-4aff-8252-641e048c296b) |
Thank you for sharing this blog template.
> Allow line breaks for <a> tags to keep body width on mobile

- contentlayer.config.ts
- data/siteMetadata.js
READY TO MERGE
<kbd>cmd+k</kbd> is now working with or without a `BASE_PATH` build option.
> `searchDocumentsPath` taking `BASE_PATH` into account

- components/ThemeSwitch.tsx
This commit addresses the issue where an error was logged in the console when the user switched between light and dark modes. The warning was caused by the inappropriate use of SVG tags in JSX. The solution involved correcting the SVG tag usage to comply with JSX syntax requirements.
Closes #974
> fix: resolve console warning when switching between light and dark modes

- layouts/ListLayoutWithTags.tsx
The timestamp between the client and Vercel server can be different giving a hydration warning. This suppresses the warning for the timestamp.
> Fix hydration warning on blog timestamp

- app/layout.tsx
- components/Header.tsx
- components/MobileNav.tsx
- css/tailwind.css
- data/siteMetadata.js
- package.json
- tailwind.config.js
- yarn.lock
This provides functionality for a fixed navbar, which can be enabled by using the `stickyNav` key in the `siteMetadata.js` file. The CSS implementation of locking the scroll (by setting the overflow property on the body element) when the mobile nav is open has been replaced with the use of the npm package [`body-scroll-lock`](https://www.npmjs.com/package/body-scroll-lock). This allows for more consistent behavior across devices and prevents the page from scrolling to the top when the nav is closed.
https://github.com/user-attachments/assets/ed9042e7-cd93-43a0-b4b3-a6996b363631
> functionality for fixed navbar

- .env.example
- README.md
- data/blog/introducing-tailwind-nextjs-starter-blog.mdx
- data/siteMetadata.js
Added beehiv in `pliny` in [this PR](https://github.com/timlrx/pliny/pull/177). After the `pliny` pr got merged beehiiv should be available in the package and this PR can be merged. 
This PR introduces information that the beehiiv newsletter api is availble in the `pliny` package and introduces the correspoinding environmental variables in the `.env.example`.
> Add beehiiv as newsletter platform

- layouts/ListLayoutWithTags.tsx
When the tag name is not in English, the original code will compare the UTF-8 encoded tag name with the original tag name, causing the tag to not be selected. This issue can be resolved by adding `decodeURI`.
> Add decodeURI to ListLayoutWithTags

- README.md
The old domain [terminals.run](terminals.run) has been deprecated. To avoid being a dead link, I have change them for new one [dreams.plus](dreams.plus)
> [update] update the new domain for blog site

- README.md
Not sure if you still accept new entries to the examples list, but [opensats.org](https://opensats.org/) is based on this project.
- https://opensats.org/blog
- https://github.com/OpenSats/website
Thanks for all the work you do!
> Add OpenSats to Examples V2

- README.md
In order to not to push everything in one PR I have separated this one change with #1046 
This PR adds my blog link as an example on the Tailwind Next.js Starter Blog.
Including my blog in the examples section provides new users with a live, functional reference of a blog created using this starter template. It can help showcase the capabilities of the template in real-world usage.
- **Example blog link**:
- Added my blog link to the examples section for easier reference by other users.
Let me know if any adjustments are needed. I hope this addition adds value to the project by demonstrating a live blog example.
> Add Schedles blog example

- README.md
This PR adds my blog link as an example on the Tailwind Next.js Starter Blog.
Including my blog in the examples section provides new users with a live, functional reference of a blog created using this starter template. It can help showcase the capabilities of the template in real-world usage.
- **Example blog link**:
- Added my blog link to the examples section for easier reference by other users.
Let me know if any adjustments are needed. I hope this addition adds value to the project by demonstrating a live blog example.
> added yawdev blog

- README.md
This PR adds my blog, [Culture DevOps](https://culturedevops.com/en), to the list of projects using this template.
The blog focuses on DevOps practices and tools, sharing technical tips and insights.
The source code is available on GitHub: [Culture DevOps GitHub](https://github.com/CultureDevOps/blog).
Let me know if there’s anything else I should adjust.
> Add Culture DevOps blog to README

- components/ThemeSwitch.tsx
`Menu.Item` and `RadioGroup.Option` are depricated, this commit updates to non-deprecated components
` { active } ` is now depricated as well, changed to ` { focus }`
[Deployment Preview](https://tailwind-nextjs-starter-blog-git-themeswichupda-7afc64-trillium.vercel.app?_vercel_share=S1bmnlWQ0wKnCPkgoM5ytOwNsktZhDLJ)
> refactor: upgrade deprecated components from @headlessui/react

- components/Header.tsx
- tailwind.config.js
When tabbing through links, focus ring for header nav links doesn't display a complete ring and has poor contrast.
`tailwind.config.js`
- Add base styles to `button` `link` in `focus-visible` state
- Add outline style
- Outline color set as primary color from tailwind config
`components/Header.tsx`
- Add pr-2 to container, m-1 to links to ensure the outline has enough roomt to display completely.
[View deployed changes](https://tailwind-nextjs-starter-blog-trillium.vercel.app/)
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details> 
Tested in (macOS):
- Chrome
- Firefox
- Safari
---
I had to push these changes with --no-verify due to husky failing pre-commit checks that are unrelated to the PR:
```
⚠ Running tasks for staged files...
❯ package.json — 2 …
```
> fix: Add outline focus-visible styles for buttons, links

- README.md
Some of the blog links in the readme are dead, lead to spam, or point to repos that have no crossover with this codebase
This PR does ✅
- Removes broken links
- Updates links to source where this codebase was used if available
This PR does not ❌
- Remove any blog links that no longer have crossover with the codebase
- Remove broken links
- [ben.codes blog](https://ben.codes)
- [CuB3y0nd's Portfolio](https://www.cubeyond.net/)
- [Frank's Tech Blog](https://frank-tech-blog.vercel.app/)
- [0xchai.io](https://0xchai.io)
- [ondiek-elijah.me](https://www.ondiek-elijah.me/)
- [https://bitoflearning-9a57.fly.dev/](https://bitoflearning-9a57.fly.dev/)
- Update typo extra "-"
- [Jigu's Blog](https://animeirl.top)
- Correct link and add codebase source link
- …
> Clean up readme links

- app/tags/[tag]/page/[page]/page.tsx
Currently when the generation for tag pagination happens, if the site is built using GitHub Pages it gives the following error: 
`[Error: Page "/tags/[tag]/page/[page]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.]`
This only occurs if there isn't enough tags to generate a second page of any tag that already exists in the blog, such as if you only have one public blog page prepared.
My first workaround to this was to modify the tags of the only blog to repeat the placeholder tag 6 times, however when checking the code more the modifications made below worked, allowing GitHub Pages to be built even when there isn't enough tags for a second page and still having proper pagination when the second page does exist.
> Tag Page Generation Patch

- package.json
- scripts/rss.mjs
- yarn.lock
SyntaxError: Unexpected identifier 'assert'
at compileSourceTextModule (node:internal/modules/esm/utils:338:16)
at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:106:18)
at #translate (node:internal/modules/esm/loader:470:12)
at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:517:27)
Node.js v23.6.0
fix issues suport the last version Node.js to build package
> fix: update build resolutions for ajv about assert

- README.md
Add New Example Blog Link
Summary
This PR adds blog link as an example on the Tailwind Next.js Starter Blog.
> Add blog link

- app/blog/[...slug]/page.tsx
When creating a new blog post the following TypeError occurs 
```
Unhandled Runtime Error
[ Server ] Error: Cannot read properties of undefined (reading 'includes')
eval
./app/blog/%5B...slug%5D/page.tsx
Module.generateMetadata
./app/blog/%5B...slug%5D/page.tsx
```
Checking that `img` is defined before calling the the `includes` method resolves the issue
> Error when creating new blog post

- layouts/ListLayout.tsx
- layouts/ListLayoutWithTags.tsx
- next.config.js
Fixes #1137
This PR fixes the issue on the regex in list layouts for removing the trailing slash used in pagination.
If `trailingSlash: true` in `next.config.js`, this will now remove the trailing slashes.
Also removed some `console.log()` messages.
> Fix for regex trialing slash if `trailingSlash: true`
